### ISSUE TITLE
Single request mock

### ISSUE THREAD

**Issue by Cherlepops** [jamielennox/requests-mock#111]
Is there a way to mock a request and leave all the others request execute normally ?

Precisely in a pytest test where multiples requests are made and only one should be mocked.

I saw that in the "send" function in adapter.py if a request doesn't have a matching mock it raise a NoMockAddress, is there a way to avoid this ?

**Comment by jamielennox** [comment]
Yea, if you set `real_http=True` on the mocker then anything that is not mocked should be sent to the real url.

https://requests-mock.readthedocs.io/en/latest/mocker.html#real-http-requests

**Comment by Cherlepops** [comment]
Thanks ! The name mislead me when I was searching this through the doc.
But since I'm in a pytest, the adapter isn't loaded through the Context Manager/Decorator and i can't add `real_http=True` in the requests_mock parameter in my tests.

Also adding it directly on my mock like :
`requests_mock.get(route, status_code=200, json=updated, real_http=True)`
Throw me a :
> RuntimeError: You should specify either response data OR real_http. Not both.

So my solution was to mock and add `real_http=True` to all requests except for one where I return data.
But is there is a way to include real_http like in pytest like in Context Manager/Decorator ?
@MeTaNoV

**Comment by jamielennox** [comment]
Hmm, I was going to say that you can just set it up as a [pytest option](https://github.com/jamielennox/requests-mock/blob/master/requests_mock/contrib/_pytest_plugin.py#L63) but it appears that's never been implementd. Pytest options are global though, so it doesn't seem like something you'd want to default the whole test suite to.

Yea, your example isn't going to work because specifying both `json` and `real_http` is saying you simultaneously want this mock to return data and send it to the real endpoint.

I'll attempt a patch to allow `real_http` to be settable via pytest options, but would that actually work for you? 

In the short term you could do: 

```
requests_mock._real_http = True
```

I'll look at making that a public option as well if you can confirm it works.

**Comment by Cherlepops** [comment]
`requests_mock._real_http = True` works fine :+1: and if ultimately `real_http` can be set in pytest options it would be great indeed

**Comment by MeTaNoV** [comment]
thx @jamielennox and @Cherlepops to take care of it, @jrypel and @rizkiaditya24 could also be interested in the topic!

**Comment by jamielennox** [comment]
I've merged this as a public property. I'm not sure that setting this globally from the pytest config file is a good idea. 

I'm going to close this for now, if you really want the pytest config please open a new bug.
