### ISSUE TITLE
Query string parameters get lost

### ISSUE THREAD

**Issue by lahwaacz** [jamielennox/requests-mock#142]
I'm trying to write tests for some code using an RPC API. The communication is done via `requests.get(some_url, params=some_params)`, but the `params` seem to get lost somewhere in the requests-mock adapter...

A simple reproducible example (using `pytest`):
```python
import requests
import requests_mock

def test_params(requests_mock):
    api_url = "mock://example.org/api.php"
    params = {'key': 'val'}
    output = {'key': ['val']}

    def api_callback(request, context):
        if not request.qs:
            context.status_code = 400
            context.reason = "No query string given"
        return request.qs
    get = requests_mock.get(api_url, json=api_callback)

    # this does not work
    response = requests.get(api_url, params=params)
    # this works
#    response = requests.get(api_url + "?key=val")

    assert response.status_code == 200
    assert response.json() == output
    assert get.called_once
    assert get.last_request.qs == output
```
The output is:
```
======================================== FAILURES ========================================
______________________________________ test_params _______________________________________

requests_mock = <requests_mock.mocker.Mocker object at 0x7fc4b2c7bdc0>

    def test_params(requests_mock):
        api_url = "mock://example.org/api.php"
        params = {'key': 'val'}
        output = {'key': ['val']}
    
        def api_callback(request, context):
            if not request.qs:
                context.status_code = 400
                context.reason = "No query string given"
            return request.qs
        get = requests_mock.get(api_url, json=api_callback)
    
        # this does not work
        response = requests.get(api_url, params=params)
        # this works
    #    response = requests.get(api_url + "?key=val")
    
>       assert response.status_code == 200
E       assert 400 == 200
E        +  where 400 = <Response [400]>.status_code

test_requests_mock.py:21: AssertionError
```

Can you help me?

**Comment by jamielennox** [comment]
Hi - I had completely forgotten about this issue and had to step through it to figure out what was going on. Basically you get caught by: https://github.com/psf/requests/blob/2d39c0db054e158767ab4a755476844fe40787e7/requests/models.py#L373-L378 which there's not a lot i can do to work around, but the good news is you shouldn't care. 

Basically it's because you're using `mock://` as the prefix. Requests only uses `params` for http calls, whilst the `?key=val` format is universal. 

I wrote the documentation that way because i expected people to use the adapter directly and not use real URLs, but the mocker actually intercepts the real calls so you don't need to do the `mock://`

if you change that to "http://example.org/api.php" it will work just fine and I really need to just start again with the documentation structure based on how people use it today.

**Comment by lahwaacz** [comment]
Oh, thanks. Using `http://` works for me.
