### ISSUE TITLE
Ability to simulate HTTP response latency

### ISSUE THREAD

**Issue by lachlan-eagling** [jamielennox/requests-mock#155]
Hi @jamielennox,

Is there currently anyway to simulate latency on a mocked http response with requests-mock? I am trying to implement some unit tests for request timeouts but  having some difficulty in mocking/simulating request latency.

Would be happy to work on this and open a PR if it was something you were open to having added, I was thinking it would be cool to have an additional kwarg for `register_uri`.

Example:
```py
with self.assertRaises(requests.exceptions.Timeout), requests_mock.Mocker() as m:
    # Simulate a 500ms delay on HTTP response.
    m.register_uri("GET", "https://httpbin.org/get", text="foo", latency=500)
    requests.get("https://httpbin.org/get")
    ...
```

**Comment by jamielennox** [comment]
Kind of, though in the unit test you've used as an example it's not going to show much. 

basically just do: 
```
   m.get('https://httpbin.org/get', exc=requests.Timeout) 
```

and then your code should ensure that it's doing the right thing on exception handling rather than try and actually time things out.

**Comment by jamielennox** [comment]
Was just looking through old tickets and I still think this is a bad idea to do in unit testing, so probably not something i want to add to the library. However if you (or future people reading this bug) are absolutely convinced you want to do this it's pretty easy to do manually. 

```
import time

import requests
import requests_mock

def delayed_response(timeout, **kwargs):
    time.sleep(timeout)
    return kwargs

with requests_mock.mock() as m:
    m.get("https://httpbin.org/get", **delayed_response(5, text="foo"))
    requests.get("https://httpbin.org/get")
```

**Comment by latk** [comment]
I've been struggling with this problem. The proposed workaround from https://github.com/jamielennox/requests-mock/issues/155#issuecomment-850071467 cannot work:

```python
def delayed_response(timeout, **kwargs):
    time.sleep(timeout)
    return kwargs

m.get("https://httpbin.org/get", **delayed_response(5, text="foo"))
```

This does not trigger the `sleep()` when creating the response, but sleeps before *registering* the mock response. The above snippet is equivalent to:

```python
time.sleep(5)
m.get("https://httpbin.org/get", text="foo")
```

What does work (in some situations) is to use a *callback* argument, e.g.:

```python
def delayed_text(timeout: float, value: str) -> str:
    time.sleep(timeout)
    return value

m.get("https://httpbin.org/get", text=delayed_text(5, "foo"))
```

However, `requests_mock` serializes all requests via a lock, and at most one mocked request will be in-flight at any time:

https://github.com/jamielennox/requests-mock/blob/9742d02a8cad17276dbeba7b300b6d27ae1b6fb1/requests_mock/mocker.py#L155-L160

That makes `requests_mock` unsuitable for testing how a concurrent client deals with slow requests. For those kinds of problems, I think I'll have to spin up a full HTTP server (e.g. via Uvicorn) so that I can use real requests. I'm using this kind of code structure:

```python
import contextlib
from concurrent.futures import ThreadPoolExecutor

import uvicorn
from starlette.applications import Starlette

@contextlib.contextmanager
def _serve_uvicorn_on_background_thread(config: uvicorn.Config) -> Iterator[str]:
    """Yields the base URL for the server."""
    # Explicitly create a socket to support port=0.
    # With port=0, the OS will assign an arbitrary free port.
    # Uvicorn can do this automatically, but doesn't expose the port number.
    # So instead, we have to create the socket ourselves.
    with (
        socket.create_server((config.host, config.port)) as sock,
        ThreadPoolExecutor(1) as pool,
    ):
        (hostname, port) = sock.getsockname()
        base_url = f"http://{hostname}:{port}"
        server = uvicorn.Server(config)
        future = pool.submit(asyncio.run, server.serve([sock]))
        try:
            yield base_url
        finally:
            server.should_exit = True  # request Uvicorn shutdown at next tick
            future.result()  # MUST be called to re-raise errors

app = Starlette(...)

with _serve_uvicorn_on_background_thread(
    uvicorn.Config(app, host="localhost", port=0, ws="none")
) as base_url:
    assert requests.get(f"{base_url}/foo", ...) == ...
```

Then, the actions in the Starlette app can sleep however they want.
