### ISSUE TITLE
mock request lists with mocker

### ISSUE THREAD

**Issue by tweigel-dev** [jamielennox/requests-mock#180]
Hay,
I want to mock a list of responses. As I see at the documentation there is only the way using the Adapter to use request lists.
Because the mocker is not able to pass response_list, as the adapter do at the register_uri function.
For me it is not clear, how to use the adapter, because at testing you do not have direct access to the session of the request to mount the mock to the session.
Do you see any possibility to mock multiple responses without mounting the mock to the session?
As I see at the mocker code. It should be able to possible to call register_uri by using the mocker. But the mock does not work. I get a "No mock address:" error, when calling the url
 
One implementation suggestion would be  not just resend I a infinite amount of responses. I saw this a nock , a javascript mocking tool. Maybe it could be a inspiration. The usage experience is very smooth and deterministic.
![image](https://user-images.githubusercontent.com/56434333/120995042-55dc2280-c785-11eb-83ee-76286f8b4484.png)

Thanks for the help in advance!

**Comment by jamielennox** [comment]
So the documentation uses adapter because that's where it was implemented and when it was written i expected adapter to be more widely used. It still references adapter because i'm not sure how else to write it, but anything that works on adapter will work on all the higher levels as well. 

using

```
with requests_mock.mock() as m: 
    m.get('http://example.com/path', response_list=[{...}]
```

or any other method or request_uri all works. The values get passed down to the adapter internally.

https://requests-mock.readthedocs.io/en/latest/response.html#response-lists
