### ISSUE TITLE
TypeError not raised when prepared request is sent without a Content-Length if requests_mock is being used

### ISSUE THREAD

**Issue by adamtheturtle** [jamielennox/requests-mock#80]
The following Python script runs without raising an `AssertionError`.
This to me was an unexpected difference between code which uses ``requests_mock`` and code which does not.

```python
import requests
import json
from requests.structures import CaseInsensitiveDict
import requests_mock

url = 'http://example.com/'
method = 'POST'

request = requests.Request(method=method, url=url, data=b'{}')
prepared_request = request.prepare()
headers = dict(prepared_request.headers)
del headers['Content-Length']

prepared_request.headers = CaseInsensitiveDict(data=headers)
session = requests.Session()

with requests_mock.mock() as m:
    m.register_uri(method, url, text='resp')
    session.send(request=prepared_request)

exception_raised = False
try:
    session.send(request=prepared_request)
except TypeError:
    exception_raised = True

assert exception_raised
```

**Comment by jamielennox** [comment]
Hi,

Thanks for the report, it's actually really good to see that the project is at the point where the bugs are interesting edge cases like this. 

It's definitely a bug, but I'm away for the holidays (without a computer!) so it'll be about 2 weeks before I get a chance to fix it. Anyone is welcome to have a go at a PR otherwise I promise to get to it then.

**Comment by jamielennox** [comment]
Hey @adamtheturtle, I think this one is on you/requests. 

If you run the above on python2 it succeeds, it fails on python3 so if anything this is something we would want to resolve in requests first. 

Second, when you delete Content-Length requeests assumes you're trying to do chunked content. In which case it assumes that the `data=` element is a list. This is why it works on python2 because `b'{}'[0]` is `'{'` and on python3 it's `123`. See https://github.com/requests/requests/blob/v2.21.0/requests/adapters.py#L469

Streaming via requests-mock is something I haven't experimented with much so I'm sure it's not perfect, but I'm not sure there's anything for me to do here.

**Comment by jamielennox** [comment]
Going to close this one as haven't heard any further.
